(function(f,h,B,t){var p=function(){function c(a){if(a&&g.u(a)){var e={name:null,A:null,c:null};if(0<=a.indexOf(".")){a=a.split(".",2);var c=a[0];a=a[1];if(!d[c])return;e.A=c}if(0<=a.indexOf(":")){a=a.split(":",2);c=a[0];a=a[1];if(!b[c])return;e.c=c}if(e.c||z.prototype[a])return e.name=a,e}}var b={},d={},a={create:function(a,b,c){if(!g.g(a))return!1;b=b||a;if(d[b])return!1;d[b]=new z(a,b,c);return!0},exec:function(a){var e=Array.prototype.slice.call(arguments,1);if("exec"===a)return!1;if(p[a])return p[a].apply(null,
e);var n=c(a);if(!n)return!1;var l=b[n.c];if(g.isArray(l))return b[n.c].push(Array.prototype.slice.call(arguments,0)),!0;if(l&&!l[n.name])return!1;for(var f=n.A?[d[n.A]]:g.values(d),h=e.length&&g.o(e[-1])?e[-1].callback:t,A=g.I(),u=!0,v=0;v<f.length;v++){var m=f[v];h&&(e[-1].callback=A.C());u=(l||m)[n.name].apply(m,e)&&u}A.complete(h);return u},get:function(a,b){b=b||function(){};"identity"===a&&w.P(m.b(function(a){b(a)}))},register:function(a,d){if(!b[a]||!g.j(d))return!1;var c=b[a];b[a]=d();setTimeout(function(){for(var a=
0;a<c.length;a++)p.exec.apply(null,c[a])});return!0},require:function(a){if(b[a])return!1;b[a]=[];x.fa("/plugins/"+a+".js");return!0},set:function(b,d){a.h=a.h||function(a,b){p.exec("associate",a,{callback:b})};switch(b){case "captureEmailForms":d?y.D(a.h):y.da(a.h)}}};return a}(),y=function(){function c(){n=function(){h.addEventListener("submit",k,!1);setTimeout(function(){h.removeEventListener("submit",k,!1)});return!0};h.addEventListener("submit",n,!0);h.addEventListener("click",a,!0)}function b(a){var b=
/\S+@\S+.\S/;a=a.getElementsByTagName("input");for(var d,c=0;c<a.length;c++)if(d=a[c],!d.hasAttribute("center-ignore")&&(d.hasAttribute("center-associate-email")||"email"===d.type||"email"===d.name.replace(/[^a-z]+/gi,"").toLowerCase()||"email"===d.id.replace(/[^a-z]+/gi,"").toLowerCase()||0<=d.className.toLowerCase().indexOf("email")))return b.test(d.value)?d.value:null;return null}function d(a,d){function c(){if(!a.H){a.H=!0;if(d){var b=h.createElement("input");b.type="hidden";b.name=d.getAttribute("name");
b.value=d.getAttribute("value");a.appendChild(b)}HTMLFormElement.prototype.submit.call(a,!0)}}try{for(var e=b(a),k=g.I(),l=0;l<r.length;l++)r[l].call(null,e,k.C());k.complete(c)}catch(f){c()}setTimeout(c,2E3)}function a(a){var b=a.target;if(b&&0<="INPUT BUTTON".indexOf(b.tagName)&&0<="submit image button".indexOf(b.type)){a=a.target;b=a;if(b.form)b=b.form;else for(;b&&"FORM"!==b.tagName;)b=b.parentElement;b&&!b.hasAttribute("center-ignore")&&(b._centerActor=a)}}function k(a){if(!1!==a.returnValue&&
!a.defaultPrevented){var c=a.target;if(c&&!c.hasAttribute("center-ignore")&&b(c))return d(c,c._centerActor),a.preventDefault(),!1}}function e(){m=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(a){if(a||this.hasAttribute("center-ignore")||!b(this))return m.call(this);d(this,null)}}var n,l=!1,m,r=[];return{D:function(a){!l&&h.addEventListener&&f.HTMLFormElement&&!l&&(c(),e(),l=!0);r.push(a)},da:function(b){b=r.indexOf(b);-1<b&&r.splice(b,1);!r.length&&l&&l&&(h.removeEventListener("submit",
n,!0),h.removeEventListener("click",a,!0),HTMLFormElement.prototype.submit=m,l=!1)}}}(),x=function(){return{G:function(c,b,d){d=d||function(){};var a={method:"GET"};a.url="https://api.leadpages.io"+c+"?"+g.S(b);var k=new XMLHttpRequest;"withCredentials"in k?(k.open(a.method,a.url,!0),k.onreadystatechange=function(){4===k.readyState&&(a.code=k.U,400<=k.status?d(k.responseText,a):d(null,a))},k.ontimeout=function(){a.U=0;d("TIMEOUT",a)},k.send()):(c=new Image,g.F(c,"load",function(){d(null,a)}),c.src=
a.url)},fa:function(c){var b=h.createElement("script");b.async=!0;b.src="https://js.center.io"+c;h.getElementsByTagName("head")[0].appendChild(b)}}}(),m=function(){var c=[],b={flush:function(){if(c.length){for(var b=[],a=[],k=[],e=0;e<c.length;e++)b.push(c[e].kind),a.push(c[e].label),k.push(c[e].value);c.length=0;b={version:"1.5.7",correlateBy:g.L("center-correlate-by")||g.M(),origin:"center-js",kind:b,label:a,value:k};x.G("/analytics/v1/observations/capture",b)}},f:function(d,a,k){c.push({kind:d,
label:a,value:k});b.B=b.B||g.V(b.flush,4E3,!1);b.B()},w:function(d,a){if(f.performance&&f.performance.getEntriesByName){var c=performance.getEntriesByName(a)[0];c&&c.duration&&b.f("timer",d,c.duration)}},ca:function(d){if(!(f.performance&&f.performance.mark&&f.performance.measure&&f.performance.getEntriesByName))return function(){};var a="center-"+d+"-s",c="center-"+d+"-e",e="center-"+d;performance.mark(a);return function(){performance.mark(c);performance.measure(e,a,c);b.w(d,e)}},R:function(d){if(d)try{var a=
{uid:g.i("centerVisitorId")||"",url:q.N(),ua:navigator.userAgent,n:(d.name||"").substr(0,100),m:(d.message||"").substr(0,100),s:(d.stack||"").replace(/\s+/gi," ").substr(0,500)};b.f("text","error",g.S(a));b.flush()}catch(c){}},b:function(d,a){a=a||f;return function(){try{return d.apply(a,arguments)}catch(c){b.R(c)}}},ga:function(d){for(var a in d)d.hasOwnProperty(a)&&g.j(d[a])&&(d[a]=b.b(d[a],d))}};return b}(),q=function(){return{W:function(){return{x:f.innerWidth||(h.documentElement||{}).clientWidth||
(h.body||{}).clientWidth||0,y:f.innerHeight||(h.documentElement||{}).clientHeight||(h.body||{}).clientHeight||0}},X:function(){return h.referrer},Y:function(c){function b(b){b=Math.abs(Math.floor(b));return(10>b?"0":"")+b}c=c||new Date;c=-c.getTimezoneOffset();return(0<=c?"+":"-")+b(c/60)+":"+b(c%60)},N:function(){return f.location.toString().replace(/ /g,"%20")},Z:function(){var c=g.K(q.$());(c=c.utm_email||c.center_email||t)&&(c=c.replace(/ /g,"+"));return c},$:function(){return f.location.search||
""}}}(),z=function(){function c(d,a,c){var e=this;e.ba=d;e.name=a;e.options=g.J(c||{},b);e.options.captureEmailForms&&y.D(function(a,b){e.associate(a,{callback:b})});e.options.captureEmailURLs&&(d=q.Z())&&e.associate(d)}var b={captureEmailForms:!1,captureEmailURLs:!0};c.prototype.associate=function(b,a){a=a||{};a.email=b;return this.send("association",null,null,null,a)};c.prototype.send=function(b,a,c,e,f){var l=this;f=g.J(f||{},l.options,{callback:function(){}});w.P(m.b(function(g){var h=q.W();g=
{k:b||"",a:a||"",l:c||"",v:e||"",e:f.email||"",pid:l.ba,uid:g.uid,sid:g.sid,uri:q.N().substr(0,1E3),rf:q.X().substr(0,500),rx:h.x,ry:h.y,tz:q.Y()};x.G("/analytics/v1/events/capture",g,function(a,b){m.w("send-events",b.url);a?(m.R({name:"HTTPError",message:b.method+" "+b.url+" "+b.U,stack:a}),m.flush(),f.callback(!1)):f.callback()})}));return!0};return c}(),g=function(){var c={F:function(b,d,a,c){b.addEventListener?b.addEventListener(d,a,c):b.attachEvent&&b.attachEvent("on"+d,a)},I:function(){return new function(){function b(){e>=
c&&d&&!a&&(a=!0,d.call(f))}var d=null,a=!1,c=0,e=0;return{C:function(){c++;return function(){e++;setTimeout(b)}},complete:function(a){d=a}}}},V:function(b,d,a){function c(){var g=this,f=Array.prototype.slice.call(arguments,0),k=a&&!e;clearTimeout(e);e=setTimeout(function(){e=null;a||b.apply(g,f)},d);k&&b.apply(g,f)}var e;c.clear=function(){clearTimeout(e);e=null};return c},J:function(b){var d=Array.prototype.slice.call(arguments,1);if(!d.length)return b;for(var a=0;a<d.length;a++)for(var c=d[a],e=
g.keys(c),f=0;f<e.length;f++){var l=e[f];b[l]===t&&(b[l]=c[l])}return b},K:function(b){if(!g.u(b))return null;var d={};b=b.replace(/(^\?)/,"").split("&");for(var a=0;a<b.length;a++){var c=b[a].split("=");if(c[1]&&0<=c[1].indexOf(","))try{d[decodeURIComponent(c[0])]=decodeURIComponent(c[1]).split(",")}catch(e){}else try{d[decodeURIComponent(c[0])]=decodeURIComponent(c[1])}catch(e){}}return d},H:function(b){return decodeURIComponent(h.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(b).replace(/[\-\.\+\*]/g,
"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},L:function(b,d){d=d||f.location.search;var a=(new RegExp("[?&]"+encodeURIComponent(b)+"(=([^&#]*)|&|#|$)")).exec(d);return a?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null},i:function(b){try{return sessionStorage.getItem(b)}catch(d){return null}},M:function(){return"xxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(){return"23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz".charAt(Math.floor(57*Math.random()))})},isArray:function(b){return!(!b||
!b.constructor||b.constructor!==Array)},j:function(b){return!(!b||"function"!==typeof b)},o:function(b){return!(!b||"object"!==typeof b)},u:function(b){return"string"===typeof b},keys:function(b){if(!g.o(b))return[];var d=[],a;for(a in b)b.hasOwnProperty(a)&&d.push(a);return d},ea:function(b,d,a,c){b.removeEventListener?b.removeEventListener(d,a,c):b.detachEvent&&b.detachEvent("on"+d,a)},S:function(b){var d="",a;for(a in b)b.hasOwnProperty(a)&&(d+="&"+encodeURIComponent(a)+"=",d=c.isArray(b[a])?d+
encodeURIComponent(b[a]).replace(/%2C/g,","):d+encodeURIComponent(b[a]));return d.substr(1,d.length)},ha:function(b,d,a,c,e){h.cookie=encodeURIComponent(b)+"="+encodeURIComponent(d)+"; expires=Fri, 31 Dec 9999 23:59:59 GMT"+(a?"; domain="+a:"")+(c?"; path="+c:"")+(e?"; secure":"")},T:function(b,c){try{return sessionStorage.setItem(b,c)}catch(a){return null}},g:function(b){return c.u(b)?/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{22}$/.test(b):!1},values:function(b){if(!g.o(b))return[];
var c=[],a;for(a in b)b.hasOwnProperty(a)&&c.push(b[a]);return c}};return c}(),w=function(){function c(){for(var c=0;c<a.length;c++)a[c].call(f,{uid:d,sid:b});a.length=0}var b=null,d=null,a=[],k={O:function(a){if(h.body){var b=m.ca("load-identify"),c=h.createElement("iframe"),d=m.b(function(h){0==="https://js.center.io".indexOf(h.origin||(h.originalEvent||{}).origin)&&(h=g.K(h.data))&&h.s&&g.g(h.id)&&(b(),g.ea(f,"message",d,!1),c.parentNode&&c.parentNode.removeChild(c),a(h))});g.F(f,"message",d,!1);
c.src="https://js.center.io/identify.html";c.style.display="none";c.style.visibility="hidden";c.style.position="absolute";c.style.left="-9999px";c.style.top="-9999px";h.body.appendChild(c)}else setTimeout(function(){k.O(a)},100)},aa:function(){b=g.i("centerSessionId");g.g(b)||(b=g.M(),g.T("centerSessionId",b));d=g.i("centerVisitorId");g.g(d)?(m.f("counter","ident-cache","1"),c()):k.O(m.b(function(a){m.f("counter",a.s,"1");d=a.id;g.T("centerVisitorId",d);c()}))},P:function(c){d?c.call(f,{uid:d,sid:b}):
a.push(c)}};return k}();m.ga(p);m.b(function(){if(null===g.L("center-no-load")){var c=f[B]||"center";f[c]=f[c]||function(){};var b=f[c].q||[];f[c]=function(a){return g.j(a)?(a(f[c]),!0):p.exec.apply(p,arguments)};f[c].hash="2ea9200b848c732bb17dd7c9bed28134f25aa926";f[c].version="1.5.7";f[c].loaded=!0;w.aa();for(var d=0;d<b.length;d++)f[c].apply(f[name],b[d]);m.w("load-center","https://js.center.io/center.js")}})()})(window,document,"LeadPagesCenterObject");
